baseURL = "https://dtz9.net/"
languageCode = "zh-cn"
title = "近视眼逛博客"
theme = "ink"
paginate = 5

copyright = "© 2019 dtz9.net"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	subtitle = ""

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[permalinks]
    post = "/:year/:month/:slug/"

[Blackfriday]
    hrefTargetBlank = "true"	

# Nav.
[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "关于"
url = "/about"
weight = 2

[[menu.main]]
name = "群组"
url = "https://t.me/link1078503"
weight = 3

[[menu.main]]
name = "友链"
url = "/links"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/1078503"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
