LanguageCode = "zh-cn"
title = "近视眼逛博客 DTZ9.NET"
hasCJKLanguage = true
theme = "tale"
paginate = "10" # Number of posts per page
summaryLength = "145"
defaultContentLanguage = "zh-cn"
publishDir = "public"
    
[Params]
  description = "逛博客、科学上网、随笔"
  subtitle = ""
  keywords = "执迷不悟,Hugo,Docker,博客,静态博客，Disqus"
  readmore = true
  dateformat = "2006-01-02"
  post_navigation = true
  post_related = true
  share_open = true
  authorbox = false
  friend_link_open = true
  toc = true
  share_top_show = true
  to_top_show = true
  

[Blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/:year/:month/:slug/"
  
[Author] # Used in authorbox
  name = "文章作者:执迷不悟"
  bio = "一个喜欢逛博客的屌丝单身老光棍儿。"
  avatar = "img/avatar.png"

[[Params.friendlink]]
  link = "https://ditou.org"
  title = "低头族"
  desc = "一个专注学习的社区" 

[[Params.friendlink]]
link = "https://dtz9.com"
  title = "影视推荐"
  desc = "DTZ9.COM"

[[Params.friendlink]]
link = "https://dtz9.org"
  title = "网址导航"
  desc = "DTZ9.ORG"      

[[Params.friendlink]]
  link = "https://youendless.com"
  title = "君无止境"
  desc = "一个专注于容器技术的博客"

[[Params.friendlink]]
  link = "http://stuit.cn/Xiaolu"
  title = "行者晓路"
  desc = "非著名历史学爱好者"   

[[Params.friendlink]]
  link = "https://cyhour.com/"
  title = "常时阳光"
  desc = ""      

[[Params.friendlink]]
  link = "http://www.wuxiaohu.cn/"
  title = "工程窝"
  desc = "伍小虎专注于建筑智能化"      

[[Params.friendlink]]
  link = "https://chriszheng.science/"
  title = "M-x Chris-An-Emacser"
  desc = "一个Emacs爱好者的闲言碎语" 


[[Params.friendlink]]
  link = "https://www.yunjinquan.com/"
  title = "景安快云"
  desc = "最新景安服务器, 快云VPS优惠"    

[[Params.friendlink]]
  link = "/links"
  title = "更多博客链接..."
  desc = "内页博客友链"   

[Params.sidebar]
  home = "right"
  list = "left"
  single = "right"
  widgets = ["search", "categories", "languages", "recent", "social", "friendlink"]

[Params.widgets]
  recent_num = 5
  tags_counter = true

[menu]
[[menu.main]]
  identifier = "post"
	name = "首页"
	url = "/"
    weight = "1"

[[menu.main]]
  identifier = "about"
	name = "关于本站"
	title = "博客随想"
	url = "/about/"
    weight = "2"

[[menu.main]]
  identifier = "telegram"
	name = "交流群组"
	url = "https://t.me/link1078503"
    weight = "3"

[[menu.main]]
  identifier = "links"
	name = "友情链接"
	title = "博客友链"
	url = "/links/"
    weight = "4"
	
[Params.widgets.social]
  email = "1078503@gmail.com"
  telegram = "link1078503"
  
[related]
   threshold = 80
   includeNewer = true
   toLower = true
   [[related.indices]]
     name = "tags"
	 weight = 100