baseurl: https://dtz9.net/
languageCode: zh-cn
defaultContentLanguage: zh-cn
title: 近视眼逛博客
author: 执迷不悟
paginate: 15
showPostSummary: true
summaryLength: 1
theme: hugo-flex

params:
  
  footer: <a href="/index.xml" title="通过订阅源快速得到本站更新通知">RSS订阅</a> · <a href="/sitemap.xml" title="为搜索引擎提供的xml格式的sitemap">站点地图</a>  · <a href="https://ditou.org" title="低头族社区" target="_blank">低头族</a>  · 本博客服务器由<a href="https://www.hostmem.com/?ref=1078503" target="_blank" title="主打洛杉矶CN2 GT线路">HostMem</a>提供 · <a href="https://img.dtz9.net/" title="低头族图床" target="_blank">免费图床</a><br><a>&copy 2019 dtz9.net</a>
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.
  dateFormat: 2006-01-02

Blackfriday:
  hrefTargetBlank: true

permalinks:
  post: /:year/:month/:slug/

menu:
  nav:
  - name: 归档
    url: post/
    weight: 1  
  - name: 标签
    url: tags/
    weight: 2
  - name: 关于
    url: about/
    weight: 3  
  - name: 群组
    url: https://t.me/link1078503
    weight: 4
  - name: 友链
    url: links/
    weight: 5
  